version: '3.8'

services:
  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334

  # FastAPI app
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./prompts:/app/prompts
      - ./.env:/app/.env
    environment:
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload

volumes:
  qdrant_storage:

